In [3]:
import numpy as np

In [4]:
# Array de 1D

d1 = np.array([1,2,3,4])
print(d1)

[1 2 3 4]


In [5]:
d1.shape # Quantas casas e dimensões 

(4,)

In [6]:
d1.ndim #Quantas dimensões 

1

In [7]:
d1.dtype # Tipo de Array

dtype('int32')

In [12]:
#Array de 2D

d2 = np.array([[1,2,3,4] , [1,2,3,4]], dtype=object)

print(d2)

[[1 2 3 4]
 [1 2 3 4]]


In [13]:
d2.shape # Quantas casas e dimensões 

(2, 4)

In [14]:
d2.ndim #Quantas dimensões 

2

In [15]:
d2.dtype # Tipo de Array

dtype('O')

In [16]:
#Array de 3D

d3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]], dtype=object)

print(d3)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [10 11 12]]]


In [17]:
d3.shape

(2, 2, 3)

In [18]:
d3.ndim

3

In [19]:
d3.dtype

dtype('O')