In [1]:
import numpy as np

In [3]:
a = np.array([[2,5,8,3], [4,6,9,2]])
print(a)

[[2 5 8 3]
 [4 6 9 2]]


In [10]:
# Para puxar um item específico, ((Nome da array)array[row, collumn])

a[0,2]

# Pode ser assim também [0,-2]

8

In [15]:
#Dá para puxar todas as colunas também 

a[1,:]

array([4, 6, 9, 2])

In [14]:
print(a[0,:])

[2 5 8 3]


In [20]:
#Puxar dados de colunas diferentes 

a[:,2]

array([8, 9])

In [22]:
b = np.array([['Alaranjada', 'Branco'], ['Avermelhado','Cinza']])
print(a)

[['Alaranjada' 'Branco']
 ['Avermelhado' 'Cinza']]


In [23]:
print(b[:,0])

['Alaranjada' 'Avermelhado']


In [24]:
b[:,1]

array(['Branco', 'Cinza'], dtype='<U11')